spring:
  application:
    name: rocketmq-comsumer
#    发送消息的配置
  cloud:
    stream:
      bindings:
        # 这里是个 Map 类型参数，{} 为 YAML 中 Map 的行内写法
        input: {destination: test-topic, content-type: application/json,group: test-group}
      rocketmq:
        binder:
          # RocketMQ 服务器地址
          namesrv-addr: 192.168.145.201:9876
server:
  port: 9094
